# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths:
      - 'apis/poi/web**'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Login to Azure
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Runs a set of commands using the runners shell
    - shell: bash
      env:
        AZURE_ACR_FQDN: ${{ secrets.AZURE_ACR_FQDN }}
      run: |
        echo "Building API-POI image..."
        echo "Changing directory to apis/poi/web..."
        cd apis/poi/web
        az acr build --image "devopsoh/api-poi:${{ github.run_number }}" --registry "$AZURE_ACR_FQDN" --file Dockerfile .
    # Deploy to preprod slot
    - name: Deploy to Azure Web App staging slot
      uses: Azure/webapps-deploy@v2
      with:
        app-name: openhackjra3xid0poi
        slot-name: staging
        images: openhackjra3xid0acr.azurecr.io/devopsoh/api-poi:${{ github.run_number }}
    # Verify that staging slot healthchecks return healthy
    - shell: bash
      env:
        AZURE_ACR_FQDN: ${{ secrets.AZURE_ACR_FQDN }}
      run: |
        echo "Checking staging slot health using /api/healthcheck/poi, if healthy then swap"
        curl https://openhackjra3xid0poi-staging.azurewebsites.net/api/healthcheck/poi        
        if [ $(curl https://openhackjra3xid0poi-staging.azurewebsites.net/api/healthcheck/poi) == "Healthy" ];then az webapp deployment slot swap -n openhackjra3xid0poi -g openhackjra3xid0rg -s staging --target-slot production;fi
      # Remove Azure session
    - name: Azure logout
      run: |
        az logout
