name: .NET Core

on:
  pull_request:
    branches: [ master ]
    # file paths to consider in the event. Optional; defaults to all.
    paths:
      - 'apis/poi/**'
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build apis/poi/poi.sln --no-restore
    - name: Test
      run: dotnet test apis/poi/tests/UnitTests/UnitTests.csproj --no-restore 
